name: Lint

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        example: [elasticsearch-module, mysql-module, parallel-containers]
    steps:
      - name: golangci-lint
        uses: golangci/golangci-lint-action@9d1e0624a798bb64f6c3cea93db47765312263dc # v5
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: v1.59.1
          # Optional: working directory, useful for monorepos
          working-directory: ${{ matrix.example }}
          # Optional: golangci-lint command line arguments.
          args: --verbose
          # Optional: if set to true then the all caching functionality will be complete disabled,
          #           takes precedence over all other caching options.
          skip-cache: true
